
### 이체 이력 쌓기 1

POST http://localhost:8080/account/transfer
Content-Type: application/json

{
  "accountNumber": "1",
  "amount": 7
}



### 이체 이력 쌓기 2

POST http://localhost:8080/account/transfer
Content-Type: application/json

{
  "accountNumber": "2",
  "amount": 100
}





### 대량 이체 이력 쌓기

POST http://localhost:8080/account/transfer/bulkcreate
Content-Type: application/json

{}

###

